-- ========================================================
-- Script de Creación de Tabla de Auditoría (audit_logs)
-- Proyecto: History-Ar (Cumplimiento Ley 26.529 & Ley 25.326)
-- Copiar y ejecutar en el SQL Editor de Supabase Dashboard
-- ========================================================

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id TEXT NOT NULL,
    accion VARCHAR(50) NOT NULL,
    paciente_id BIGINT REFERENCES public.pacientes(id) ON DELETE SET NULL,
    detalle TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    ip VARCHAR(100),
    user_agent TEXT
);

-- Habilitar RLS en audit_logs
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Permitir inserción de logs por usuarios autenticados y anónimos de la API
CREATE POLICY "Permitir insercion de logs de auditoria" 
ON public.audit_logs 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Permitir lectura únicamente a médicos autenticados
CREATE POLICY "Medicos ven registros de auditoria" 
ON public.audit_logs 
FOR SELECT 
TO authenticated 
USING (true);
