-- Script DDL para creación de tablas en Supabase PostgreSQL (History-Ar)

-- 1. Tabla de Usuarios (Médicos)
CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    especialidad TEXT,
    matricula TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    firma_ruta TEXT,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Pacientes
CREATE TABLE IF NOT EXISTS public.pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    apellido TEXT NOT NULL,
    dni TEXT NOT NULL UNIQUE,
    fecha_nacimiento TEXT NOT NULL,
    telefono TEXT,
    email TEXT,
    direccion TEXT,
    obra_social TEXT,
    numero_afiliado TEXT,
    notas_generales TEXT,
    usuario_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla de Consultas (Historias Clínicas / Padecimientos)
CREATE TABLE IF NOT EXISTS public.consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    motivo TEXT NOT NULL,
    diagnostico TEXT NOT NULL,
    tratamiento TEXT NOT NULL,
    notas TEXT,
    paciente_id BIGINT NOT NULL REFERENCES public.pacientes(id) ON DELETE CASCADE
);

-- 4. Tabla de Recetas Médicas
CREATE TABLE IF NOT EXISTS public.recetas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    medicamentos TEXT NOT NULL,
    indicaciones TEXT,
    paciente_id BIGINT NOT NULL REFERENCES public.pacientes(id) ON DELETE CASCADE,
    consulta_id BIGINT REFERENCES public.consultas(id) ON DELETE SET NULL
);

-- 5. Tabla de Citas / Agenda
CREATE TABLE IF NOT EXISTS public.citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora TIMESTAMPTZ NOT NULL,
    duracion_minutos INTEGER DEFAULT 30,
    motivo TEXT NOT NULL,
    estado TEXT DEFAULT 'programado',
    paciente_id BIGINT NOT NULL REFERENCES public.pacientes(id) ON DELETE CASCADE
);

-- 6. Tabla de Documentos Adjuntos
CREATE TABLE IF NOT EXISTS public.documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_subida TIMESTAMPTZ DEFAULT NOW(),
    nombre TEXT NOT NULL,
    ruta_archivo TEXT NOT NULL,
    tipo_mimetype TEXT NOT NULL,
    paciente_id BIGINT NOT NULL REFERENCES public.pacientes(id) ON DELETE CASCADE,
    consulta_id BIGINT REFERENCES public.consultas(id) ON DELETE SET NULL
);

-- 7. Tabla de Medicamentos Personalizados (Vademécum Custom)
CREATE TABLE IF NOT EXISTS public.medicamentos_custom (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comercial TEXT NOT NULL,
    monodroga TEXT,
    presentacion TEXT,
    dosis_sugerida TEXT,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS y otorgar políticas de acceso abierto para la clave pública (anon)
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recetas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.citas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medicamentos_custom ENABLE ROW LEVEL SECURITY;

-- Eliminar políticas antiguas si existen
DROP POLICY IF EXISTS "Allow anon all on usuarios" ON public.usuarios;
DROP POLICY IF EXISTS "Allow anon all on pacientes" ON public.pacientes;
DROP POLICY IF EXISTS "Allow anon all on consultas" ON public.consultas;
DROP POLICY IF EXISTS "Allow anon all on recetas" ON public.recetas;
DROP POLICY IF EXISTS "Allow anon all on citas" ON public.citas;
DROP POLICY IF EXISTS "Allow anon all on documentos" ON public.documentos;
DROP POLICY IF EXISTS "Allow anon all on medicamentos_custom" ON public.medicamentos_custom;

-- Crear políticas universales de lectura/escritura para la clave anon de Supabase
CREATE POLICY "Allow anon all on usuarios" ON public.usuarios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon all on pacientes" ON public.pacientes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon all on consultas" ON public.consultas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon all on recetas" ON public.recetas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon all on citas" ON public.citas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon all on documentos" ON public.documentos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon all on medicamentos_custom" ON public.medicamentos_custom FOR ALL USING (true) WITH CHECK (true);

